let array1 = ["item1","item2","item3"];
let array2 = array1.slice(0);
let array3 = [].concat(array1);
//spread operator..
let array4 = [...array1];
console.log(array1);
console.log(array2);
console.log(array3);
console.log(array4);
array2 = [...array1, "item4" , "item5"];
console.log(array2);
array1.push("item4");
console.log("After Updating");
console.log(array1);
console.log(array2);
console.log(array3);
console.log(array4);
console.log(array1===array2);
array2 = [...array1, "item4" , "item5"];
console.log(array2);
let array5 = [...array1, ...array2];
console.log(array5);